### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by SlaunchaMan** [Flight-School/Money#1]
It would be nice to use this from CocoaPods! Here’s a rough draft of a `Podspec` that seems to work, albeit with a warning that the summary and description are identical:

```Ruby
Pod::Spec.new do |s|
  
  s.name         = "Money"
  s.version      = "1.0.0"
  s.summary      = "A precise, type-safe representation of a monetary amount in a given currency."

  s.description  = <<-DESC
A precise, type-safe representation of a monetary amount in a given currency.
                   DESC

  s.homepage     = "https://gumroad.com/l/swift-numbers"
  s.license      = { :type => "MIT", :file => "LICENSE.md" }


  s.author             = "Mattt"
  s.social_media_url   = "http://twitter.com/mattt"

  s.swift_version = '4.0'
  s.ios.deployment_target = "8.0"
  s.osx.deployment_target = "10.10"
  s.watchos.deployment_target = "2.0"
  s.tvos.deployment_target = "9.0"

  s.source       = { :git => "https://github.com/Flight-School/Money.git", :tag => "#{s.version}" }

  s.source_files  = "Sources/Money/*.swift"

end
```

**Comment by mattt** [comment]
Apologies for not responding sooner, @SlaunchaMan. Thanks for taking the time to write up a quick podspec — I appreciate that.

I have some concerns about the logistics of publishing via CocoaPods, which I've outlined in #5. If you have any suggestions, I'd be very happy to hear them.

**Comment by mattt** [comment]
Following the conventions from @flight-school/AnyCodable to work around namespacing issues, I just released this to CocoaPods under the name [Money-FlightSchool](https://cocoapods.org/pods/Money-FlightSchool).
