### ISSUE TITLE
Instantiate based on currencyCode

### ISSUE THREAD

**Issue by moetanahy** [Flight-School/Money#14]
Hi,

I'm not sure if this is the best place to ask this question so bear with me in case this is more of a feature request or just not understanding the library clearly.

**Some Background**

I am building an app and all currency values are stored and passed in API's using Minor Values (e.g. cents or pence as needed by the currency).  I'm using similar libraries for JavaScript and the Backend to be able to manage this.

I was looking for a similar library to understand and use this on Swift.

**Usage**

I have two steps in what I'm trying to do.

(1) Creating a Money<Currency> value based on a currencyCode which is passed as a string.

I sense this is something I'm not fully understanding in Swift, but how do I instantiate the  Money<USD> with the "USD" actually being a string?

(2) Creating the value from a Minor Value

I considered creating this as an extension of your class, which would need to do the following:
* Understanding which currency is being converted using the currencyCode, then finding the CurrencyType enum which matches this currencyCode
* Using the CurrencyType. minorUnit to understand how many decimal places there are for this currency and split the integer into a decimal with the correct values (maybe via a string concatenation).
However, in this case the factory will have to know if it's returning a USD or GBP ... in the return type which causes a compilation error.

Again, apologies if there is something I'm not understanding, but any help or guidance would be much appreciated.

Thanks

Moe

**Comment by mattt** [comment]
@moetanahy Thanks for taking a look at this library. I'll try my best to answer your questions:

> (1) Creating a Money value based on a currencyCode which is passed as a string.
>
> I sense this is something I'm not fully understanding in Swift, but how do I instantiate the Money with the "USD" actually being a string?

This library doesn't provide a built-in function to get `CurrencyType` from strings (e.g. `"USD"` → `USD.self`). There are a few reasons for this decision:

1. Any such function wouldn't automatically cover any new currency types defined by the user, which may cause unexpected issues.
2. Decoding dynamic values from the user or from a server have inherent risks, which are especially important whenever money is involved.

Most apps work in a small number of currencies. For those apps, I'd recommend using a `switch` statement like this:

```swift
let currency: CurrencyType.Type
let currencyCode: String = "USD" 
switch currencyCode {
case "USD":
   currency = USD.self
default:
  // handle other values
}
```

> (2) Creating the value from a Minor Value
> 
> I considered creating this as an extension of your class, which would need to do the following:
> * Understanding which currency is being converted using the currencyCode, then finding the CurrencyType enum which matches this currencyCode
> * Using the CurrencyType. minorUnit to understand how many decimal places there are for this currency and split the integer into a decimal with the correct values (maybe via a string concatenation).
> However, in this case the factory will have to know if it's returning a USD or GBP ... in the return type which causes a compilation error.

Here's how you might initialize a money value from a quantity of its currency's minor units:

```swift
extension Money {
    public init(minorUnits: Int) {
        precondition(Currency.minorUnit >= 0)

        let sign: FloatingPointSign = minorUnits >= 0 ? .plus : .minus
        let exponent = -Currency.minorUnit
        let significand = Decimal(minorUnits)

        let amount = Decimal(sign: sign, exponent: exponent, significand: significand)
        self.init(amount)
    }
}

// Example usage:
let twoCents = Money<USD>(minorUnits: 2) // $0.02
```

I haven't tested this extensively, so _caveat emptor_. If that's generally useful, I may add this as a built-in function.

As far as resolving types, please see the README sections ["Supporting Multiple Currencies"](https://github.com/Flight-School/Money#supporting-multiple-currencies) and ["Alternatives to Consider"](https://github.com/Flight-School/Money#alternatives-to-consider).

**Comment by mattt** [comment]
Following up on this —

I just merged #15 and #16, which add initialization from minor units and a helper function that returns built-in currency types from their three-letter code.

**Comment by moetanahy** [comment]
That's awesome Matt.  Thanks for the update!

**Comment by NSCabezon** [comment]
Hi, I hope you don't mind asking a small question here, it's regarding the same topic as question nº1.

from the `Price` example in the documentation, I was trying to make that implement Decodable in order to decode it from a JSON, but I think It can't make it i think because of the CurrencyType.Type, any tip on how to get around this?

Thanks,
Iván

**Comment by mattt** [comment]
@NSCabezon It's not pretty, but it's possible to decode a `Price`. Here's a rough idea of what you could do: 

```swift
protocol Price: Codable {
    var amount: Decimal { get }
    var currency: CurrencyType.Type { get }
}

extension Money: Price {}

struct Product: Codable {
    var price: Price

    init(price: Price) {
        self.price = price
    }

    private enum CodingKeys: String, CodingKey {
        case price
    }

    private enum NestedCodingKeys: String, CodingKey {
        case amount
        case currencyCode
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let nestedContainer = try container.nestedContainer(keyedBy: NestedCodingKeys.self, forKey: .price)
        let currencyCode = try nestedContainer.decode(String.self, forKey: .currencyCode)
        switch currencyCode {
        case USD.code:
            self.price = try container.decode(Money<USD>.self, forKey: .price)
        // ...
        default:
            throw DecodingError.dataCorruptedError(forKey: .currencyCode, in: nestedContainer, debugDescription: "unknown currency code: \(currencyCode)")
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        var nestedContainer = container.nestedContainer(keyedBy: NestedCodingKeys.self, forKey: .price)
        try nestedContainer.encode(price.currency.code, forKey: .currencyCode)
        try nestedContainer.encode(price.amount, forKey: .amount)
    }
}
```

**Comment by lvandyk** [comment]
Hi @mattt firstly thank you for creating such an awesome package.

What I'm trying to do:

```
let currencyCode = getCurrencyCodeFromSomewhere() // Can be ZAR, USD, GBP etc..
let currency = iso4217Currency(for: currencyCode)
let money = Money<currency>(minorUnits: 100) // Here I cannot pass the currency type as a generic
```

I basically want to instantiate `Money` using a `CurrencyType` from `iso4217Currency`. Is this possible or do I have to have a massive switch statement?

**Comment by mattt** [comment]
@lvandyk Unfortunately, I don't know of a way to instantiate a Swift generic type like `Money` from a value determined at runtime. So yes, I believe a large `switch` statement is the only way to do this.
