### ISSUE TITLE
Change "currencyCode" JSON coding key to "currency"

### ISSUE THREAD

**Issue by EthanLozano** [Flight-School/Money#18]
Please make the "currencyCode" JSON key configurable to "currency", or please change this key to "currency" for better compatibility between libraries.

The JSON serialization/deserialization of a Money object does not seem to be configurable to another key besides "currencyCode". Whereas, "currency" seems to be the preferred default JSON key for money libraries in other languages (i.e. [jackson-datatype-money](https://github.com/zalando/jackson-datatype-money) & [dinero](https://github.com/dinerojs/dinero.js)). Also, not every library can be configured to use "currencyCode" as the JSON key, and "currency" is a shorter key that offers minor savings in bandwidth and storage costs.

**Comment by mattt** [comment]
Hi @EthanLozano. Thanks for your feedback.

The lack of flexibility in Swift's Codable to customize object mappings is one of my least favorite aspects of its design. However, there are a few different approaches to work around / within these constraints.

Thanks for proposing #19. That's definitely a valid approach to solving the problem you described. I just pushed #21 as an alternative that makes some different trade-offs.

As for #20, there's a good argument for making the coding key value `"currency"` — and that's probably what it should've been from the start. At this point, though, I think stability trumps any potential upside to changing now.

Feel free to take a look at #21 and let me know what you think. Thanks again!
